### ISSUE TITLE
erreur dans l'activation de l'app

### ISSUE THREAD

**Issue by jcsjerome** [CNRS-DSI-Dev/user_share_guest#1]
Bonjour, j'ai cette erreur lorsque j'essaye d'activer l'app :

[Doctrine\DBAL\DBALException]
  An exception occurred while executing 'CREATE TABLE `oc_user_guest` (`uid` VARCHAR(64) NOT NULL, `accepted` TINYINT(1) DEFAULT '0' NOT NULL, `is_ac
  tive` TINYINT(1) DEFAULT '0' NOT NULL, `date_creation` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, `date_expiration` DATETIME DEFAULT '9999-12-31
  00:00:00' NOT NULL, `token` VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date_creation'

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date_creation'

**Comment by Alenore** [comment]
Bonjour,

Quelle est la version de la base de données utilisée ? C'est fonctionnel avec un MariaDB 10.0.14 et sur un MySQL 5.6.23. Cela n'est effectivement pas fonctionnel sur des versions plus anciennes, donc nous allons appliquer un correctif pour gérer la DEFAULT via le code.

**Comment by jcsjerome** [comment]
Nous sommes en MariaDB 5.5
Cordialement.

**Comment by Victor-Bordage-Gorry** [comment]
Bonjour,
Un fix a été livré, l'application devrait s'installer normalement maintenant.
Cordialement

**Comment by jcsjerome** [comment]
ça fonctionne.
